// <auto-generated />
namespace SIGSE.Context.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class inicial1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(inicial1));
        
        string IMigrationMetadata.Id
        {
            get { return "202211192106511_inicial1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
