// <auto-generated />
namespace SIGSE.Context.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class inicial2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(inicial2));
        
        string IMigrationMetadata.Id
        {
            get { return "202211130236418_inicial2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
